# Generated by Django 3.0.5 on 2020-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('energy', models.DecimalField(decimal_places=3, max_digits=7)),
                ('reactiveEnergy', models.DecimalField(decimal_places=3, max_digits=7)),
                ('power', models.DecimalField(decimal_places=3, max_digits=7)),
                ('maximeter', models.DecimalField(decimal_places=3, max_digits=7)),
                ('reactivePower', models.DecimalField(decimal_places=3, max_digits=7)),
                ('voltage', models.DecimalField(decimal_places=3, max_digits=7)),
                ('intensity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('powerFactor', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
    ]
